modLoader="javafml"
loaderVersion="[42,)"
license="All Rights Reserved"

[[mods]]
modId="mo_enchants"
version="1.5-RELEASE+1.19.2MC"
displayName="Mo' Enchants"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-enchants"
logoFile="logo.png"
authors="LDM"
description='''
Adds more enchantments and curses to Minecraft!
'''

[[dependencies.mo_enchants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




